; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -verify-machineinstrs -wasm-disable-explicit-locals -wasm-keep-registers -mattr=+simd128,+relaxed-simd | FileCheck %s --check-prefix=RELAXED
; RUN: llc < %s -verify-machineinstrs -wasm-disable-explicit-locals -wasm-keep-registers -mattr=+simd128               | FileCheck %s --check-prefix=SIMD

target triple = "wasm32-unknown-unknown"

define <16 x i8> @swizzle_v16i8(<16 x i8> %a, <16 x i8> %b) {
; RELAXED-LABEL: swizzle_v16i8:
; RELAXED:         .functype swizzle_v16i8 (v128, v128) -> (v128)
; RELAXED-NEXT:  # %bb.0:
; RELAXED-NEXT:    i8x16.relaxed_swizzle $push0=, $0, $1
; RELAXED-NEXT:    # fallthrough-return
;
; SIMD-LABEL: swizzle_v16i8:
; SIMD:         .functype swizzle_v16i8 (v128, v128) -> (v128)
; SIMD-NEXT:  # %bb.0:
; SIMD-NEXT:    i8x16.swizzle $push0=, $0, $1
; SIMD-NEXT:    # fallthrough-return
  %res = call <16 x i8> @llvm.wasm.swizzle(<16 x i8> %a, <16 x i8> %b)
  ret <16 x i8> %res
}

declare <16 x i8> @llvm.wasm.swizzle(<16 x i8>, <16 x i8>)
